name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/build.yml'
      - '!.github/workflows/lint.yml'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/release.yml'
      - '**.md'
      - .editorconfig
      - .gitignore
      - '.idea/**'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/build.yml'
      - '!.github/workflows/lint.yml'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/release.yml'
      - '**.md'
      - .editorconfig
      - .gitignore
      - '.idea/**'
      - '.vscode/**'

jobs:
  build:
    strategy:
        fail-fast: true
        matrix:
          os: 
            - macos-latest
            # - ubuntu-latest
            # - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn compile


